In [1]:
# Importing the necessary libraries.

import re
import numpy as np
import pandas as pd
from pandas.api.types import CategoricalDtype
import matplotlib.pyplot as plt
import yfinance as yf

In [2]:
# Loading the data, assigning my names to tickers.

data = {}
tickers = ['RY4C.DE', 'EZJ.L', 'WIZZ.L', 'LHA.DE', 'AF.PA', 'IAG.L', 'BZ=F', 'GBPEUR=X', 'EUR=X']
my_names = ['ryanair', 'easyjet', 'wizzair', 'lufthansa', 'airfrance', 'iag', 'brent', 'gbpeur', 'usdeur']

assert len(tickers) == len(my_names)

for ticker, name in zip(tickers, my_names):
    df = yf.download(ticker, start = '2019-01-01', end = '2026-08-26')
    data[name] = df

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [3]:
# Checking the structure of the dataframes.

for key, value in data.items():
    display(key, value)

'ryanair'

Price           Close       High        Low       Open  Volume
Ticker        RY4C.DE    RY4C.DE    RY4C.DE    RY4C.DE RY4C.DE
Date
2019-01-02   9.914224   9.923666   9.720660   9.819802   24940
2019-01-03   9.961435  10.079462   9.890620   9.980319   17167
2019-01-04   9.772593  10.036972   9.772593   9.895339   23132
2019-01-07  10.206931  10.206931   9.838688  10.088905    7682
2019-01-08  10.320236  10.320236   9.848130   9.923667    4863
...               ...        ...        ...        ...     ...
2026-08-19  23.250000  24.200001  22.969999  24.200001   17135
2026-08-20  22.990000  24.150000  22.580000  24.150000   23900
2026-08-21  23.500000  23.549999  23.030001  23.400000    7922
2026-08-24  23.160000  23.809999  23.100000  23.500000   18057
2026-08-25  23.510000  24.059999  23.450001  24.059999    4772

[1944 rows x 5 columns]

'easyjet'

Price             Close         High          Low         Open   Volume
Ticker            EZJ.L        EZJ.L        EZJ.L        EZJ.L    EZJ.L
Date
2019-01-02  1100.453613  1129.912217  1075.987993  1109.940282  1424927
2019-01-03  1084.475830  1120.924603  1083.976532  1096.458988  1536053
2019-01-04  1105.446411  1105.446411  1078.484304  1089.468866  2279479
2019-01-07  1098.456299  1121.424021  1096.459106  1110.439458  3446572
2019-01-08  1145.889526  1161.867071  1087.471629  1091.466015  2908500
...                 ...          ...          ...          ...      ...
2026-08-19   670.200012   674.599976   669.200012   674.599976  5812726
2026-08-20   670.799988   674.000000   669.599976   672.000000  4505935
2026-08-21   671.000000   674.000000   667.400024   673.000000  5359772
2026-08-24   673.799988   675.400024   671.799988   673.599976  3777491
2026-08-25   676.000000   680.000000   672.000000   675.000000  7154231

[1932 rows x 5 columns]

'wizzair'

Price        Close    High     Low    Open  Volume
Ticker      WIZZ.L  WIZZ.L  WIZZ.L  WIZZ.L  WIZZ.L
Date
2019-01-02  2752.0  2812.0  2703.0  2787.0  291417
2019-01-03  2777.0  2863.0  2767.0  2790.0  223224
2019-01-04  2905.0  2905.0  2770.0  2819.0  268074
2019-01-07  2929.0  2973.0  2886.0  2917.0  449709
2019-01-08  2925.0  2977.0  2872.0  2926.0  229536
...            ...     ...     ...     ...     ...
2026-08-19  1051.0  1071.0  1040.0  1043.0  374549
2026-08-20  1033.0  1057.0  1023.0  1050.0  445533
2026-08-21  1060.0  1062.0  1034.0  1035.0  312633
2026-08-24  1059.0  1084.0  1055.0  1075.0  372688
2026-08-25  1085.0  1087.0  1056.0  1056.0  630467

[1932 rows x 5 columns]

'lufthansa'

Price           Close       High        Low       Open   Volume
Ticker         LHA.DE     LHA.DE     LHA.DE     LHA.DE   LHA.DE
Date
2019-01-02  11.882315  12.047556  11.774157  11.978454  4470439
2019-01-03  11.572864  12.071591  11.533807  11.825232  5565657
2019-01-04  11.885319  11.909353  11.638959  11.699047  4585005
2019-01-07  11.906351  12.071592  11.819224  11.996482  4008106
2019-01-08  12.089618  12.378038  11.870298  11.966438  6094122
...               ...        ...        ...        ...      ...
2026-08-19   7.852000   7.920000   7.836000   7.880000  2650648
2026-08-20   7.618000   7.866000   7.604000   7.852000  5143992
2026-08-21   7.606000   7.682000   7.576000   7.650000  7208816
2026-08-24   7.786000   7.816000   7.578000   7.638000  4491675
2026-08-25   7.982000   8.050000   7.840000   7.844000  5288313

[1944 rows x 5 columns]

'airfrance'

Price           Close       High        Low       Open   Volume
Ticker          AF.PA      AF.PA      AF.PA      AF.PA    AF.PA
Date
2019-01-02  46.813557  47.721382  46.410076  47.388512   491659
2019-01-03  45.875469  47.781902  45.764511  46.803471   606939
2019-01-04  46.742947  47.075817  45.461903  46.642078   559640
2019-01-07  47.681034  48.397209  46.753033  46.894253   512468
2019-01-08  48.649380  49.305035  47.317902  47.711296   544552
...               ...        ...        ...        ...      ...
2026-08-19  11.755000  11.940000  11.700000  11.810000   811936
2026-08-20  11.380000  11.780000  11.365000  11.685000  1115227
2026-08-21  11.500000  11.550000  11.265000  11.380000  1095651
2026-08-24  11.625000  11.625000  11.400000  11.460000  1476849
2026-08-25  12.065000  12.265000  11.825000  11.825000  1459875

[1959 rows x 5 columns]

'iag'

Price            Close        High         Low        Open    Volume
Ticker           IAG.L       IAG.L       IAG.L       IAG.L     IAG.L
Date
2019-01-02  604.263977  606.459800  598.674449  600.870333   4537405
2019-01-03  580.508606  618.636936  580.508606  599.872226   6795077
2019-01-04  590.689514  595.081282  581.906039  587.894780   4278054
2019-01-07  595.480469  604.264004  591.687612  597.476716   3411969
2019-01-08  595.879761  602.467352  587.096286  598.874131   5906737
...                ...         ...         ...         ...       ...
2026-08-19  427.600006  432.000000  423.799988  426.899994   6451126
2026-08-20  418.700012  428.750000  416.799988  427.700012   7713245
2026-08-21  422.899994  425.500000  420.100006  420.799988   7754056
2026-08-24  432.200012  432.549988  423.000000  423.399994   5647481
2026-08-25  441.899994  444.700012  434.200012  436.200012  10135293

[1927 rows x 5 columns]

'brent'

Price           Close       High        Low       Open Volume
Ticker           BZ=F       BZ=F       BZ=F       BZ=F   BZ=F
Date
2019-01-02  54.910000  56.560001  52.500000  54.250000  43517
2019-01-03  55.950001  56.290001  53.930000  54.770000  36535
2019-01-04  57.060001  58.299999  55.360001  55.580002  42426
2019-01-07  57.330002  58.919998  57.279999  57.369999  41677
2019-01-08  58.720001  58.860001  57.110001  57.630001  34135
...               ...        ...        ...        ...    ...
2026-08-19  91.620003  92.800003  90.419998  91.309998  28039
2026-08-20  93.779999  94.720001  91.349998  91.510002  27355
2026-08-21  94.389999  94.809998  92.769997  93.330002  16522
2026-08-24  92.169998  93.800003  91.779999  93.680000  18474
2026-08-25  88.580002  92.839996  86.089996  92.180000  19467

[1925 rows x 5 columns]

'gbpeur'

Price         Close     High      Low     Open   Volume
Ticker     GBPEUR=X GBPEUR=X GBPEUR=X GBPEUR=X GBPEUR=X
Date
2019-01-01  1.10790  1.11240  1.09740  1.11000        0
2019-01-02  1.11264  1.11324  1.10710  1.11254        0
2019-01-03  1.10570  1.10887  1.10300  1.10610        0
2019-01-04  1.10851  1.11650  1.10740  1.10849        0
2019-01-07  1.11593  1.11656  1.11215  1.11576        0
...             ...      ...      ...      ...      ...
2026-08-19  1.16928  1.16933  1.16590  1.16921        0
2026-08-20  1.16497  1.16784  1.16430  1.16492        0
2026-08-21  1.16727  1.16801  1.16600  1.16721        0
2026-08-24  1.16875  1.16941  1.16770  1.16868        0
2026-08-25  1.16878  1.16996  1.16780  1.16872        0

[1991 rows x 5 columns]

'usdeur'

Price         Close     High       Low     Open Volume
Ticker        EUR=X    EUR=X     EUR=X    EUR=X  EUR=X
Date
2019-01-01  0.87009  0.87222  0.865800  0.87000      0
2019-01-02  0.87247  0.88139  0.869792  0.87250      0
2019-01-03  0.88354  0.88360  0.876490  0.88360      0
2019-01-04  0.87788  0.88120  0.875830  0.87789      0
2019-01-07  0.87639  0.87679  0.871500  0.87620      0
...             ...      ...       ...      ...    ...
2026-08-19  0.86360  0.86413  0.856300  0.86379      0
2026-08-20  0.85662  0.85688  0.853900  0.85650      0
2026-08-21  0.85559  0.85690  0.853800  0.85561      0
2026-08-24  0.85605  0.85757  0.855300  0.85580      0
2026-08-25  0.85702  0.85824  0.856500  0.85701      0

[1990 rows x 5 columns]

In [4]:
# Formatting structure of the dataframes.

def format_structure(df):
    """
    Basic formatting of the structure, resetting index, removing multiindex,
    assigning names to dataframe index.
    Dropping unnecessary columns for the analysis e.g high, low columns
    and also volume for the proxy dataframes such as brent, gbpeur and usdeur
    which are only needed for the conversion to EUR currency.
    Adding separate name columns for future use on merging.
    
    """
    for key in df.keys():
        df[key] = df[key].reset_index()
        df[key].columns = df[key].columns.droplevel(1)
        df[key].columns.name = key
        df[key]['name'] = key
        df[key].columns = df[key].columns.str.strip().str.lower()
        if key in ['brent', 'gbpeur', 'usdeur']:
            df[key] = df[key].drop(columns = ['high', 'low', 'volume'])
            df[key] = df[key][['date', 'open', 'close', 'name']]
        else:
            df[key] = df[key].drop(columns = ['high', 'low'])
            df[key] = df[key][['date', 'open', 'close', 'volume', 'name']]
        df[key] = df[key].sort_values('date')
    return df

format_structure(data)

{'ryanair': ryanair       date       open      close  volume     name
 0       2019-01-02   9.819802   9.914224   24940  ryanair
 1       2019-01-03   9.980319   9.961435   17167  ryanair
 2       2019-01-04   9.895339   9.772593   23132  ryanair
 3       2019-01-07  10.088905  10.206931    7682  ryanair
 4       2019-01-08   9.923667  10.320236    4863  ryanair
 ...            ...        ...        ...     ...      ...
 1939    2026-08-19  24.200001  23.250000   17135  ryanair
 1940    2026-08-20  24.150000  22.990000   23900  ryanair
 1941    2026-08-21  23.400000  23.500000    7922  ryanair
 1942    2026-08-24  23.500000  23.160000   18057  ryanair
 1943    2026-08-25  24.059999  23.510000    4772  ryanair

 [1944 rows x 5 columns],
 'easyjet': easyjet       date         open        close   volume     name
 0       2019-01-02  1109.940282  1100.453613  1424927  easyjet
 1       2019-01-03  1096.458988  1084.475830  1536053  easyjet
 2       2019-01-04  1089.468866  1105.446411  2279479  easyjet
 3       2019-01-07  1110.439458  1098.456299  3446572  easyjet
 4       2019-01-08  1091.466015  1145.889526  2908500  easyjet
 ...            ...          ...          ...      ...      ...
 1927    2026-08-19   674.599976   670.200012  5812726  easyjet
 1928    2026-08-20   672.000000   670.799988  4505935  easyjet
 1929    2026-08-21   673.000000   671.000000  5359772  easyjet
 1930    2026-08-24   673.599976   673.799988  3777491  easyjet
 1931    2026-08-25   675.000000   676.000000  7154231  easyjet

 [1932 rows x 5 columns],
 'wizzair': wizzair       date    open   close  volume     name
 0       2019-01-02  2787.0  2752.0  291417  wizzair
 1       2019-01-03  2790.0  2777.0  223224  wizzair
 2       2019-01-04  2819.0  2905.0  268074  wizzair
 3       2019-01-07  2917.0  2929.0  449709  wizzair
 4       2019-01-08  2926.0  2925.0  229536  wizzair
 ...            ...     ...     ...     ...      ...
 1927    2026-08-19  1043.0  1051.0  374549  wizzair
 1928    2026-08-20  1050.0  1033.0  445533  wizzair
 1929    2026-08-21  1035.0  1060.0  312633  wizzair
 1930    2026-08-24  1075.0  1059.0  372688  wizzair
 1931    2026-08-25  1056.0  1085.0  630467  wizzair

 [1932 rows x 5 columns],
 'lufthansa': lufthansa       date       open      close   volume       name
 0         2019-01-02  11.978454  11.882315  4470439  lufthansa
 1         2019-01-03  11.825232  11.572864  5565657  lufthansa
 2         2019-01-04  11.699047  11.885319  4585005  lufthansa
 3         2019-01-07  11.996482  11.906351  4008106  lufthansa
 4         2019-01-08  11.966438  12.089618  6094122  lufthansa
 ...              ...        ...        ...      ...        ...
 1939      2026-08-19   7.880000   7.852000  2650648  lufthansa
 1940      2026-08-20   7.852000   7.618000  5143992  lufthansa
 1941      2026-08-21   7.650000   7.606000  7208816  lufthansa
 1942      2026-08-24   7.638000   7.786000  4491675  lufthansa
 1943      2026-08-25   7.844000   7.982000  5288313  lufthansa

 [1944 rows x 5 columns],
 'airfrance': airfrance       date       open      close   volume       name
 0         2019-01-02  47.388512  46.813557   491659  airfrance
 1         2019-01-03  46.803471  45.875469   606939  airfrance
 2         2019-01-04  46.642078  46.742947   559640  airfrance
 3         2019-01-07  46.894253  47.681034   512468  airfrance
 4         2019-01-08  47.711296  48.649380   544552  airfrance
 ...              ...        ...        ...      ...        ...
 1954      2026-08-19  11.810000  11.755000   811936  airfrance
 1955      2026-08-20  11.685000  11.380000  1115227  airfrance
 1956      2026-08-21  11.380000  11.500000  1095651  airfrance
 1957      2026-08-24  11.460000  11.625000  1476849  airfrance
 1958      2026-08-25  11.825000  12.065000  1459875  airfrance

 [1959 rows x 5 columns],
 'iag': iag        date        open       close    volume name
 0    2019-01-02  600.870333  604.263977   4537405  iag
 1    2019-01-03  599.872226  580.508606   6795077  iag
 2    2019-01-04  587.894780  590.689514   4278054  iag
 3    2019-01-07  597.476716  595.480469   3411969  iag
 4    2019-01-08  598.874131  595.879761   5906737  iag
 ...         ...         ...         ...       ...  ...
 1922 2026-08-19  426.899994  427.600006   6451126  iag
 1923 2026-08-20  427.700012  418.700012   7713245  iag
 1924 2026-08-21  420.799988  422.899994   7754056  iag
 1925 2026-08-24  423.399994  432.200012   5647481  iag
 1926 2026-08-25  436.200012  441.899994  10135293  iag

 [1927 rows x 5 columns],
 'brent': brent       date       open      close   name
 0     2019-01-02  54.250000  54.910000  brent
 1     2019-01-03  54.770000  55.950001  brent
 2     2019-01-04  55.580002  57.060001  brent
 3     2019-01-07  57.369999  57.330002  brent
 4     2019-01-08  57.630001  58.720001  brent
 ...          ...        ...        ...    ...
 1920  2026-08-19  91.309998  91.620003  brent
 1921  2026-08-20  91.510002  93.779999  brent
 1922  2026-08-21  93.330002  94.389999  brent
 1923  2026-08-24  93.680000  92.169998  brent
 1924  2026-08-25  92.180000  88.580002  brent

 [1925 rows x 4 columns],
 'gbpeur': gbpeur       date     open    close    name
 0      2019-01-01  1.11000  1.10790  gbpeur
 1      2019-01-02  1.11254  1.11264  gbpeur
 2      2019-01-03  1.10610  1.10570  gbpeur
 3      2019-01-04  1.10849  1.10851  gbpeur
 4      2019-01-07  1.11576  1.11593  gbpeur
 ...           ...      ...      ...     ...
 1986   2026-08-19  1.16921  1.16928  gbpeur
 1987   2026-08-20  1.16492  1.16497  gbpeur
 1988   2026-08-21  1.16721  1.16727  gbpeur
 1989   2026-08-24  1.16868  1.16875  gbpeur
 1990   2026-08-25  1.16872  1.16878  gbpeur

 [1991 rows x 4 columns],
 'usdeur': usdeur       date     open    close    name
 0      2019-01-01  0.87000  0.87009  usdeur
 1      2019-01-02  0.87250  0.87247  usdeur
 2      2019-01-03  0.88360  0.88354  usdeur
 3      2019-01-04  0.87789  0.87788  usdeur
 4      2019-01-07  0.87620  0.87639  usdeur
 ...           ...      ...      ...     ...
 1985   2026-08-19  0.86379  0.86360  usdeur
 1986   2026-08-20  0.85650  0.85662  usdeur
 1987   2026-08-21  0.85561  0.85559  usdeur
 1988   2026-08-24  0.85580  0.85605  usdeur
 1989   2026-08-25  0.85701  0.85702  usdeur

 [1990 rows x 4 columns]}

In [5]:
# Checking new structure

for key in data.keys():
    display(data[key])

ryanair       date       open      close  volume     name
0       2019-01-02   9.819802   9.914224   24940  ryanair
1       2019-01-03   9.980319   9.961435   17167  ryanair
2       2019-01-04   9.895339   9.772593   23132  ryanair
3       2019-01-07  10.088905  10.206931    7682  ryanair
4       2019-01-08   9.923667  10.320236    4863  ryanair
...            ...        ...        ...     ...      ...
1939    2026-08-19  24.200001  23.250000   17135  ryanair
1940    2026-08-20  24.150000  22.990000   23900  ryanair
1941    2026-08-21  23.400000  23.500000    7922  ryanair
1942    2026-08-24  23.500000  23.160000   18057  ryanair
1943    2026-08-25  24.059999  23.510000    4772  ryanair

[1944 rows x 5 columns]

easyjet       date         open        close   volume     name
0       2019-01-02  1109.940282  1100.453613  1424927  easyjet
1       2019-01-03  1096.458988  1084.475830  1536053  easyjet
2       2019-01-04  1089.468866  1105.446411  2279479  easyjet
3       2019-01-07  1110.439458  1098.456299  3446572  easyjet
4       2019-01-08  1091.466015  1145.889526  2908500  easyjet
...            ...          ...          ...      ...      ...
1927    2026-08-19   674.599976   670.200012  5812726  easyjet
1928    2026-08-20   672.000000   670.799988  4505935  easyjet
1929    2026-08-21   673.000000   671.000000  5359772  easyjet
1930    2026-08-24   673.599976   673.799988  3777491  easyjet
1931    2026-08-25   675.000000   676.000000  7154231  easyjet

[1932 rows x 5 columns]

wizzair       date    open   close  volume     name
0       2019-01-02  2787.0  2752.0  291417  wizzair
1       2019-01-03  2790.0  2777.0  223224  wizzair
2       2019-01-04  2819.0  2905.0  268074  wizzair
3       2019-01-07  2917.0  2929.0  449709  wizzair
4       2019-01-08  2926.0  2925.0  229536  wizzair
...            ...     ...     ...     ...      ...
1927    2026-08-19  1043.0  1051.0  374549  wizzair
1928    2026-08-20  1050.0  1033.0  445533  wizzair
1929    2026-08-21  1035.0  1060.0  312633  wizzair
1930    2026-08-24  1075.0  1059.0  372688  wizzair
1931    2026-08-25  1056.0  1085.0  630467  wizzair

[1932 rows x 5 columns]

lufthansa       date       open      close   volume       name
0         2019-01-02  11.978454  11.882315  4470439  lufthansa
1         2019-01-03  11.825232  11.572864  5565657  lufthansa
2         2019-01-04  11.699047  11.885319  4585005  lufthansa
3         2019-01-07  11.996482  11.906351  4008106  lufthansa
4         2019-01-08  11.966438  12.089618  6094122  lufthansa
...              ...        ...        ...      ...        ...
1939      2026-08-19   7.880000   7.852000  2650648  lufthansa
1940      2026-08-20   7.852000   7.618000  5143992  lufthansa
1941      2026-08-21   7.650000   7.606000  7208816  lufthansa
1942      2026-08-24   7.638000   7.786000  4491675  lufthansa
1943      2026-08-25   7.844000   7.982000  5288313  lufthansa

[1944 rows x 5 columns]

airfrance       date       open      close   volume       name
0         2019-01-02  47.388512  46.813557   491659  airfrance
1         2019-01-03  46.803471  45.875469   606939  airfrance
2         2019-01-04  46.642078  46.742947   559640  airfrance
3         2019-01-07  46.894253  47.681034   512468  airfrance
4         2019-01-08  47.711296  48.649380   544552  airfrance
...              ...        ...        ...      ...        ...
1954      2026-08-19  11.810000  11.755000   811936  airfrance
1955      2026-08-20  11.685000  11.380000  1115227  airfrance
1956      2026-08-21  11.380000  11.500000  1095651  airfrance
1957      2026-08-24  11.460000  11.625000  1476849  airfrance
1958      2026-08-25  11.825000  12.065000  1459875  airfrance

[1959 rows x 5 columns]

iag        date        open       close    volume name
0    2019-01-02  600.870333  604.263977   4537405  iag
1    2019-01-03  599.872226  580.508606   6795077  iag
2    2019-01-04  587.894780  590.689514   4278054  iag
3    2019-01-07  597.476716  595.480469   3411969  iag
4    2019-01-08  598.874131  595.879761   5906737  iag
...         ...         ...         ...       ...  ...
1922 2026-08-19  426.899994  427.600006   6451126  iag
1923 2026-08-20  427.700012  418.700012   7713245  iag
1924 2026-08-21  420.799988  422.899994   7754056  iag
1925 2026-08-24  423.399994  432.200012   5647481  iag
1926 2026-08-25  436.200012  441.899994  10135293  iag

[1927 rows x 5 columns]

brent       date       open      close   name
0     2019-01-02  54.250000  54.910000  brent
1     2019-01-03  54.770000  55.950001  brent
2     2019-01-04  55.580002  57.060001  brent
3     2019-01-07  57.369999  57.330002  brent
4     2019-01-08  57.630001  58.720001  brent
...          ...        ...        ...    ...
1920  2026-08-19  91.309998  91.620003  brent
1921  2026-08-20  91.510002  93.779999  brent
1922  2026-08-21  93.330002  94.389999  brent
1923  2026-08-24  93.680000  92.169998  brent
1924  2026-08-25  92.180000  88.580002  brent

[1925 rows x 4 columns]

gbpeur       date     open    close    name
0      2019-01-01  1.11000  1.10790  gbpeur
1      2019-01-02  1.11254  1.11264  gbpeur
2      2019-01-03  1.10610  1.10570  gbpeur
3      2019-01-04  1.10849  1.10851  gbpeur
4      2019-01-07  1.11576  1.11593  gbpeur
...           ...      ...      ...     ...
1986   2026-08-19  1.16921  1.16928  gbpeur
1987   2026-08-20  1.16492  1.16497  gbpeur
1988   2026-08-21  1.16721  1.16727  gbpeur
1989   2026-08-24  1.16868  1.16875  gbpeur
1990   2026-08-25  1.16872  1.16878  gbpeur

[1991 rows x 4 columns]

usdeur       date     open    close    name
0      2019-01-01  0.87000  0.87009  usdeur
1      2019-01-02  0.87250  0.87247  usdeur
2      2019-01-03  0.88360  0.88354  usdeur
3      2019-01-04  0.87789  0.87788  usdeur
4      2019-01-07  0.87620  0.87639  usdeur
...           ...      ...      ...     ...
1985   2026-08-19  0.86379  0.86360  usdeur
1986   2026-08-20  0.85650  0.85662  usdeur
1987   2026-08-21  0.85561  0.85559  usdeur
1988   2026-08-24  0.85580  0.85605  usdeur
1989   2026-08-25  0.85701  0.85702  usdeur

[1990 rows x 4 columns]

In [6]:
# Currency conversion

def currency_conversion(df):
    for key in df.keys():
        if key in ['easyjet', 'wizzair', 'iag']:
            df[key][['open', 'close']] = df[key][['open', 'close']] / 100 # Converting GBp to GBP
            df[key] = pd.merge(df[key], df['gbpeur'], on = 'date', how = 'left', suffixes = (f'_{key}', '_gbpeur')) # Merging for calculations
            df[key][f'open_{key}'] = df[key][f'open_{key}'] * df[key]['open_gbpeur'] # Converting open price
            df[key][f'close_{key}'] = df[key][f'close_{key}'] * df[key]['close_gbpeur'] # Converting close price
            df[key] = df[key].drop(columns = ['open_gbpeur', 'close_gbpeur', 'name_gbpeur']) # Dropping unnecessary columns
            df[key] = df[key].rename(columns = {f'open_{key}': 'open', f'close_{key}': 'close', f'name_{key}': 'name'}) # Renaming columns
            df[key].columns.name = key # Assigning column names
        elif key in ['brent']:
            df[key] = pd.merge(df[key], df['usdeur'], on = 'date', how = 'left', suffixes = (f'_{key}', '_usdeur'))
            df[key][f'open_{key}'] = df[key][f'open_{key}'] * df[key]['open_usdeur']
            df[key][f'close_{key}'] = df[key][f'close_{key}'] * df[key]['close_usdeur']
            df[key] = df[key].drop(columns = ['open_usdeur', 'close_usdeur', 'name_usdeur'])
            df[key] = df[key].rename(columns = {f'open_{key}': 'open', f'close_{key}': 'close', f'name_{key}': 'name'})
            df[key].columns.name = key
    return df

currency_conversion(data)

{'ryanair': ryanair       date       open      close  volume     name
 0       2019-01-02   9.819802   9.914224   24940  ryanair
 1       2019-01-03   9.980319   9.961435   17167  ryanair
 2       2019-01-04   9.895339   9.772593   23132  ryanair
 3       2019-01-07  10.088905  10.206931    7682  ryanair
 4       2019-01-08   9.923667  10.320236    4863  ryanair
 ...            ...        ...        ...     ...      ...
 1939    2026-08-19  24.200001  23.250000   17135  ryanair
 1940    2026-08-20  24.150000  22.990000   23900  ryanair
 1941    2026-08-21  23.400000  23.500000    7922  ryanair
 1942    2026-08-24  23.500000  23.160000   18057  ryanair
 1943    2026-08-25  24.059999  23.510000    4772  ryanair

 [1944 rows x 5 columns],
 'easyjet': easyjet       date       open      close   volume     name
 0       2019-01-02  12.348530  12.244087  1424927  easyjet
 1       2019-01-03  12.127932  11.991049  1536053  easyjet
 2       2019-01-04  12.076653  12.253984  2279479  easyjet
 3       2019-01-07  12.389839  12.258003  3446572  easyjet
 4       2019-01-08  12.156203  12.760855  2908500  easyjet
 ...            ...        ...        ...      ...      ...
 1927    2026-08-19   7.887490   7.836515  5812726  easyjet
 1928    2026-08-20   7.828262   7.814619  4505935  easyjet
 1929    2026-08-21   7.855323   7.832381  5359772  easyjet
 1930    2026-08-24   7.872228   7.875038  3777491  easyjet
 1931    2026-08-25   7.888860   7.900953  7154231  easyjet

 [1932 rows x 5 columns],
 'wizzair': wizzair       date       open      close  volume     name
 0       2019-01-02  31.006490  30.619853  291417  wizzair
 1       2019-01-03  30.860189  30.705289  223224  wizzair
 2       2019-01-04  31.248333  32.202216  268074  wizzair
 3       2019-01-07  32.546718  32.685589  449709  wizzair
 4       2019-01-08  32.588324  32.573386  229536  wizzair
 ...            ...        ...        ...     ...      ...
 1927    2026-08-19  12.194860  12.289133  374549  wizzair
 1928    2026-08-20  12.231660  12.034141  445533  wizzair
 1929    2026-08-21  12.080623  12.373061  312633  wizzair
 1930    2026-08-24  12.563309  12.377063  372688  wizzair
 1931    2026-08-25  12.341683  12.681263  630467  wizzair

 [1932 rows x 5 columns],
 'lufthansa': lufthansa       date       open      close   volume       name
 0         2019-01-02  11.978454  11.882315  4470439  lufthansa
 1         2019-01-03  11.825232  11.572864  5565657  lufthansa
 2         2019-01-04  11.699047  11.885319  4585005  lufthansa
 3         2019-01-07  11.996482  11.906351  4008106  lufthansa
 4         2019-01-08  11.966438  12.089618  6094122  lufthansa
 ...              ...        ...        ...      ...        ...
 1939      2026-08-19   7.880000   7.852000  2650648  lufthansa
 1940      2026-08-20   7.852000   7.618000  5143992  lufthansa
 1941      2026-08-21   7.650000   7.606000  7208816  lufthansa
 1942      2026-08-24   7.638000   7.786000  4491675  lufthansa
 1943      2026-08-25   7.844000   7.982000  5288313  lufthansa

 [1944 rows x 5 columns],
 'airfrance': airfrance       date       open      close   volume       name
 0         2019-01-02  47.388512  46.813557   491659  airfrance
 1         2019-01-03  46.803471  45.875469   606939  airfrance
 2         2019-01-04  46.642078  46.742947   559640  airfrance
 3         2019-01-07  46.894253  47.681034   512468  airfrance
 4         2019-01-08  47.711296  48.649380   544552  airfrance
 ...              ...        ...        ...      ...        ...
 1954      2026-08-19  11.810000  11.755000   811936  airfrance
 1955      2026-08-20  11.685000  11.380000  1115227  airfrance
 1956      2026-08-21  11.380000  11.500000  1095651  airfrance
 1957      2026-08-24  11.460000  11.625000  1476849  airfrance
 1958      2026-08-25  11.825000  12.065000  1459875  airfrance

 [1959 rows x 5 columns],
 'iag': iag        date      open     close    volume name
 0    2019-01-02  6.684923  6.723283   4537405  iag
 1    2019-01-03  6.635186  6.418684   6795077  iag
 2    2019-01-04  6.516755  6.547852   4278054  iag
 3    2019-01-07  6.666406  6.645145   3411969  iag
 4    2019-01-08  6.669961  6.635836   5906737  iag
 ...         ...       ...       ...       ...  ...
 1922 2026-08-19  4.991357  4.999842   6451126  iag
 1923 2026-08-20  4.982363  4.877730   7713245  iag
 1924 2026-08-21  4.911619  4.936385   7754056  iag
 1925 2026-08-24  4.948191  5.051338   5647481  iag
 1926 2026-08-25  5.097957  5.164839  10135293  iag

 [1927 rows x 5 columns],
 'brent': brent       date       open      close   name
 0     2019-01-02  47.333125  47.907329  brent
 1     2019-01-03  48.394772  49.434062  brent
 2     2019-01-04  48.793127  50.091833  brent
 3     2019-01-07  50.267594  50.243439  brent
 4     2019-01-08  50.203222  51.150994  brent
 ...          ...        ...        ...    ...
 1920  2026-08-19  78.872661  79.123036  brent
 1921  2026-08-20  78.378320  80.333824  brent
 1922  2026-08-21  79.854084  80.759138  brent
 1923  2026-08-24  80.171342  78.902128  brent
 1924  2026-08-25  78.999183  75.914835  brent

 [1925 rows x 4 columns],
 'gbpeur': gbpeur       date     open    close    name
 0      2019-01-01  1.11000  1.10790  gbpeur
 1      2019-01-02  1.11254  1.11264  gbpeur
 2      2019-01-03  1.10610  1.10570  gbpeur
 3      2019-01-04  1.10849  1.10851  gbpeur
 4      2019-01-07  1.11576  1.11593  gbpeur
 ...           ...      ...      ...     ...
 1986   2026-08-19  1.16921  1.16928  gbpeur
 1987   2026-08-20  1.16492  1.16497  gbpeur
 1988   2026-08-21  1.16721  1.16727  gbpeur
 1989   2026-08-24  1.16868  1.16875  gbpeur
 1990   2026-08-25  1.16872  1.16878  gbpeur

 [1991 rows x 4 columns],
 'usdeur': usdeur       date     open    close    name
 0      2019-01-01  0.87000  0.87009  usdeur
 1      2019-01-02  0.87250  0.87247  usdeur
 2      2019-01-03  0.88360  0.88354  usdeur
 3      2019-01-04  0.87789  0.87788  usdeur
 4      2019-01-07  0.87620  0.87639  usdeur
 ...           ...      ...      ...     ...
 1985   2026-08-19  0.86379  0.86360  usdeur
 1986   2026-08-20  0.85650  0.85662  usdeur
 1987   2026-08-21  0.85561  0.85559  usdeur
 1988   2026-08-24  0.85580  0.85605  usdeur
 1989   2026-08-25  0.85701  0.85702  usdeur

 [1990 rows x 4 columns]}

In [7]:
# Checking the results.

for key in data.keys():
    display(data[key])

ryanair       date       open      close  volume     name
0       2019-01-02   9.819802   9.914224   24940  ryanair
1       2019-01-03   9.980319   9.961435   17167  ryanair
2       2019-01-04   9.895339   9.772593   23132  ryanair
3       2019-01-07  10.088905  10.206931    7682  ryanair
4       2019-01-08   9.923667  10.320236    4863  ryanair
...            ...        ...        ...     ...      ...
1939    2026-08-19  24.200001  23.250000   17135  ryanair
1940    2026-08-20  24.150000  22.990000   23900  ryanair
1941    2026-08-21  23.400000  23.500000    7922  ryanair
1942    2026-08-24  23.500000  23.160000   18057  ryanair
1943    2026-08-25  24.059999  23.510000    4772  ryanair

[1944 rows x 5 columns]

easyjet       date       open      close   volume     name
0       2019-01-02  12.348530  12.244087  1424927  easyjet
1       2019-01-03  12.127932  11.991049  1536053  easyjet
2       2019-01-04  12.076653  12.253984  2279479  easyjet
3       2019-01-07  12.389839  12.258003  3446572  easyjet
4       2019-01-08  12.156203  12.760855  2908500  easyjet
...            ...        ...        ...      ...      ...
1927    2026-08-19   7.887490   7.836515  5812726  easyjet
1928    2026-08-20   7.828262   7.814619  4505935  easyjet
1929    2026-08-21   7.855323   7.832381  5359772  easyjet
1930    2026-08-24   7.872228   7.875038  3777491  easyjet
1931    2026-08-25   7.888860   7.900953  7154231  easyjet

[1932 rows x 5 columns]

wizzair       date       open      close  volume     name
0       2019-01-02  31.006490  30.619853  291417  wizzair
1       2019-01-03  30.860189  30.705289  223224  wizzair
2       2019-01-04  31.248333  32.202216  268074  wizzair
3       2019-01-07  32.546718  32.685589  449709  wizzair
4       2019-01-08  32.588324  32.573386  229536  wizzair
...            ...        ...        ...     ...      ...
1927    2026-08-19  12.194860  12.289133  374549  wizzair
1928    2026-08-20  12.231660  12.034141  445533  wizzair
1929    2026-08-21  12.080623  12.373061  312633  wizzair
1930    2026-08-24  12.563309  12.377063  372688  wizzair
1931    2026-08-25  12.341683  12.681263  630467  wizzair

[1932 rows x 5 columns]

lufthansa       date       open      close   volume       name
0         2019-01-02  11.978454  11.882315  4470439  lufthansa
1         2019-01-03  11.825232  11.572864  5565657  lufthansa
2         2019-01-04  11.699047  11.885319  4585005  lufthansa
3         2019-01-07  11.996482  11.906351  4008106  lufthansa
4         2019-01-08  11.966438  12.089618  6094122  lufthansa
...              ...        ...        ...      ...        ...
1939      2026-08-19   7.880000   7.852000  2650648  lufthansa
1940      2026-08-20   7.852000   7.618000  5143992  lufthansa
1941      2026-08-21   7.650000   7.606000  7208816  lufthansa
1942      2026-08-24   7.638000   7.786000  4491675  lufthansa
1943      2026-08-25   7.844000   7.982000  5288313  lufthansa

[1944 rows x 5 columns]

airfrance       date       open      close   volume       name
0         2019-01-02  47.388512  46.813557   491659  airfrance
1         2019-01-03  46.803471  45.875469   606939  airfrance
2         2019-01-04  46.642078  46.742947   559640  airfrance
3         2019-01-07  46.894253  47.681034   512468  airfrance
4         2019-01-08  47.711296  48.649380   544552  airfrance
...              ...        ...        ...      ...        ...
1954      2026-08-19  11.810000  11.755000   811936  airfrance
1955      2026-08-20  11.685000  11.380000  1115227  airfrance
1956      2026-08-21  11.380000  11.500000  1095651  airfrance
1957      2026-08-24  11.460000  11.625000  1476849  airfrance
1958      2026-08-25  11.825000  12.065000  1459875  airfrance

[1959 rows x 5 columns]

iag        date      open     close    volume name
0    2019-01-02  6.684923  6.723283   4537405  iag
1    2019-01-03  6.635186  6.418684   6795077  iag
2    2019-01-04  6.516755  6.547852   4278054  iag
3    2019-01-07  6.666406  6.645145   3411969  iag
4    2019-01-08  6.669961  6.635836   5906737  iag
...         ...       ...       ...       ...  ...
1922 2026-08-19  4.991357  4.999842   6451126  iag
1923 2026-08-20  4.982363  4.877730   7713245  iag
1924 2026-08-21  4.911619  4.936385   7754056  iag
1925 2026-08-24  4.948191  5.051338   5647481  iag
1926 2026-08-25  5.097957  5.164839  10135293  iag

[1927 rows x 5 columns]

brent       date       open      close   name
0     2019-01-02  47.333125  47.907329  brent
1     2019-01-03  48.394772  49.434062  brent
2     2019-01-04  48.793127  50.091833  brent
3     2019-01-07  50.267594  50.243439  brent
4     2019-01-08  50.203222  51.150994  brent
...          ...        ...        ...    ...
1920  2026-08-19  78.872661  79.123036  brent
1921  2026-08-20  78.378320  80.333824  brent
1922  2026-08-21  79.854084  80.759138  brent
1923  2026-08-24  80.171342  78.902128  brent
1924  2026-08-25  78.999183  75.914835  brent

[1925 rows x 4 columns]

gbpeur       date     open    close    name
0      2019-01-01  1.11000  1.10790  gbpeur
1      2019-01-02  1.11254  1.11264  gbpeur
2      2019-01-03  1.10610  1.10570  gbpeur
3      2019-01-04  1.10849  1.10851  gbpeur
4      2019-01-07  1.11576  1.11593  gbpeur
...           ...      ...      ...     ...
1986   2026-08-19  1.16921  1.16928  gbpeur
1987   2026-08-20  1.16492  1.16497  gbpeur
1988   2026-08-21  1.16721  1.16727  gbpeur
1989   2026-08-24  1.16868  1.16875  gbpeur
1990   2026-08-25  1.16872  1.16878  gbpeur

[1991 rows x 4 columns]

usdeur       date     open    close    name
0      2019-01-01  0.87000  0.87009  usdeur
1      2019-01-02  0.87250  0.87247  usdeur
2      2019-01-03  0.88360  0.88354  usdeur
3      2019-01-04  0.87789  0.87788  usdeur
4      2019-01-07  0.87620  0.87639  usdeur
...           ...      ...      ...     ...
1985   2026-08-19  0.86379  0.86360  usdeur
1986   2026-08-20  0.85650  0.85662  usdeur
1987   2026-08-21  0.85561  0.85559  usdeur
1988   2026-08-24  0.85580  0.85605  usdeur
1989   2026-08-25  0.85701  0.85702  usdeur

[1990 rows x 4 columns]

In [8]:
# Checking for outliers, weird values.

for key in data.keys():
    display(data[key].describe())

ryanair                 date         open        close         volume
count                   1944  1944.000000  1944.000000    1944.000000
mean     2022-10-29 04:05:55    15.981110    15.991901   25844.802984
min      2019-01-02 00:00:00     7.833180     7.921937       0.000000
25%      2020-12-01 18:00:00    11.961984    12.043422   10355.000000
50%      2022-10-27 12:00:00    15.055458    15.090866   18944.500000
75%      2024-09-20 18:00:00    18.371962    18.413712   32011.250000
max      2026-08-25 00:00:00    29.375737    29.454597  507791.000000
std                      NaN     5.057887     5.026174   28073.097748

easyjet                 date         open        close        volume
count                   1932  1932.000000  1932.000000  1.932000e+03
mean     2022-10-28 09:01:51     7.506551     7.499091  4.932320e+06
min      2019-01-02 00:00:00     3.238363     3.221147  2.605580e+05
25%      2020-11-25 18:00:00     5.489490     5.483676  2.722694e+06
50%      2022-10-27 12:00:00     6.211516     6.191906  3.980562e+06
75%      2024-09-26 06:00:00     9.043618     8.967633  6.067651e+06
max      2026-08-25 00:00:00    18.423385    18.353440  4.626703e+07
std                      NaN     3.210538     3.207396  3.529920e+06

wizzair                 date         open        close        volume
count                   1932  1932.000000  1932.000000  1.932000e+03
mean     2022-10-28 09:01:51    31.119175    31.130763  5.564879e+05
min      2019-01-02 00:00:00     9.834892     9.766787  8.973000e+03
25%      2020-11-25 18:00:00    18.356632    18.252374  2.711860e+05
50%      2022-10-27 12:00:00    29.988658    29.994342  4.267460e+05
75%      2024-09-26 06:00:00    39.838766    39.885094  6.674152e+05
max      2026-08-25 00:00:00    65.304838    65.004765  1.542553e+07
std                      NaN    14.263510    14.280598  6.423409e+05

lufthansa                 date         open        close        volume
count                     1944  1944.000000  1944.000000  1.944000e+03
mean       2022-10-29 04:05:55     7.165949     7.158797  6.974188e+06
min        2019-01-02 00:00:00     4.470636     4.409343  0.000000e+00
25%        2020-12-01 18:00:00     5.793187     5.784175  3.933744e+06
50%        2022-10-27 12:00:00     6.675637     6.668377  5.438038e+06
75%        2024-09-20 18:00:00     8.157194     8.128500  7.980856e+06
max        2026-08-25 00:00:00    14.096543    14.126585  5.396341e+07
std                        NaN     1.918877     1.917500  5.303906e+06

airfrance                 date         open        close        volume
count                     1959  1959.000000  1959.000000  1.959000e+03
mean       2022-10-26 15:37:12    20.290812    20.256912  1.268212e+06
min        2019-01-02 00:00:00     7.062000     7.050000  0.000000e+00
25%        2020-11-28 12:00:00    11.296000    11.283500  6.930660e+05
50%        2022-10-24 00:00:00    15.595000    15.560000  1.043766e+06
75%        2024-09-21 12:00:00    22.877213    22.698169  1.550662e+06
max        2026-08-25 00:00:00    60.673031    64.203468  1.792524e+07
std                        NaN    13.308364    13.315987  9.584381e+05

iag                   date         open        close        volume
count                 1927  1927.000000  1927.000000  1.927000e+03
mean   2022-10-26 04:24:32     3.103351     3.099885  2.295073e+07
min    2019-01-02 00:00:00     0.990866     1.002407  7.766750e+05
25%    2020-11-24 12:00:00     1.786521     1.781348  1.173252e+07
50%    2022-10-25 00:00:00     2.248433     2.241278  1.882884e+07
75%    2024-09-21 12:00:00     4.474912     4.456074  2.839214e+07
max    2026-08-25 00:00:00     7.848957     7.874017  1.860300e+08
std                    NaN     1.730521     1.730223  1.733814e+07

brent                 date         open        close
count                 1925  1923.000000  1923.000000
mean   2022-10-27 20:34:17    66.413705    66.428894
min    2019-01-02 00:00:00    18.015346    17.791332
25%    2020-11-27 00:00:00    55.725950    55.756307
50%    2022-10-26 00:00:00    66.221154    66.178295
75%    2024-09-25 00:00:00    77.429129    77.405200
max    2026-08-25 00:00:00   118.862343   117.787680
std                    NaN    17.921254    17.929639

gbpeur                 date         open        close
count                  1991  1991.000000  1991.000000
mean    2022-10-25 15:06:14     1.157071     1.157061
min     2019-01-01 00:00:00     1.060750     1.060330
25%     2020-11-26 12:00:00     1.141775     1.141780
50%     2022-10-25 00:00:00     1.159910     1.159890
75%     2024-09-19 12:00:00     1.174260     1.174270
max     2026-08-25 00:00:00     1.214920     1.214920
std                     NaN     0.027378     0.027383

usdeur                 date         open        close
count                  1990  1990.000000  1990.000000
mean    2022-10-26 06:12:39     0.896989     0.896975
min     2019-01-01 00:00:00     0.810520     0.810300
25%     2020-11-27 18:00:00     0.860905     0.860923
50%     2022-10-25 12:00:00     0.896745     0.896735
75%     2024-09-19 18:00:00     0.923960     0.923900
max     2026-08-25 00:00:00     1.042080     1.042080
std                     NaN     0.043225     0.043232

In [9]:
# Dropping entries with 0 volume.


def drop_zero_volume_entries(df):
    for key in df.keys():
        try:
            df[key] = df[key][df[key]['volume'] > 0]
        except KeyError:
            continue
    return df

drop_zero_volume_entries(data)

{'ryanair': ryanair       date       open      close  volume     name
 0       2019-01-02   9.819802   9.914224   24940  ryanair
 1       2019-01-03   9.980319   9.961435   17167  ryanair
 2       2019-01-04   9.895339   9.772593   23132  ryanair
 3       2019-01-07  10.088905  10.206931    7682  ryanair
 4       2019-01-08   9.923667  10.320236    4863  ryanair
 ...            ...        ...        ...     ...      ...
 1939    2026-08-19  24.200001  23.250000   17135  ryanair
 1940    2026-08-20  24.150000  22.990000   23900  ryanair
 1941    2026-08-21  23.400000  23.500000    7922  ryanair
 1942    2026-08-24  23.500000  23.160000   18057  ryanair
 1943    2026-08-25  24.059999  23.510000    4772  ryanair

 [1943 rows x 5 columns],
 'easyjet': easyjet       date       open      close   volume     name
 0       2019-01-02  12.348530  12.244087  1424927  easyjet
 1       2019-01-03  12.127932  11.991049  1536053  easyjet
 2       2019-01-04  12.076653  12.253984  2279479  easyjet
 3       2019-01-07  12.389839  12.258003  3446572  easyjet
 4       2019-01-08  12.156203  12.760855  2908500  easyjet
 ...            ...        ...        ...      ...      ...
 1927    2026-08-19   7.887490   7.836515  5812726  easyjet
 1928    2026-08-20   7.828262   7.814619  4505935  easyjet
 1929    2026-08-21   7.855323   7.832381  5359772  easyjet
 1930    2026-08-24   7.872228   7.875038  3777491  easyjet
 1931    2026-08-25   7.888860   7.900953  7154231  easyjet

 [1932 rows x 5 columns],
 'wizzair': wizzair       date       open      close  volume     name
 0       2019-01-02  31.006490  30.619853  291417  wizzair
 1       2019-01-03  30.860189  30.705289  223224  wizzair
 2       2019-01-04  31.248333  32.202216  268074  wizzair
 3       2019-01-07  32.546718  32.685589  449709  wizzair
 4       2019-01-08  32.588324  32.573386  229536  wizzair
 ...            ...        ...        ...     ...      ...
 1927    2026-08-19  12.194860  12.289133  374549  wizzair
 1928    2026-08-20  12.231660  12.034141  445533  wizzair
 1929    2026-08-21  12.080623  12.373061  312633  wizzair
 1930    2026-08-24  12.563309  12.377063  372688  wizzair
 1931    2026-08-25  12.341683  12.681263  630467  wizzair

 [1932 rows x 5 columns],
 'lufthansa': lufthansa       date       open      close   volume       name
 0         2019-01-02  11.978454  11.882315  4470439  lufthansa
 1         2019-01-03  11.825232  11.572864  5565657  lufthansa
 2         2019-01-04  11.699047  11.885319  4585005  lufthansa
 3         2019-01-07  11.996482  11.906351  4008106  lufthansa
 4         2019-01-08  11.966438  12.089618  6094122  lufthansa
 ...              ...        ...        ...      ...        ...
 1939      2026-08-19   7.880000   7.852000  2650648  lufthansa
 1940      2026-08-20   7.852000   7.618000  5143992  lufthansa
 1941      2026-08-21   7.650000   7.606000  7208816  lufthansa
 1942      2026-08-24   7.638000   7.786000  4491675  lufthansa
 1943      2026-08-25   7.844000   7.982000  5288313  lufthansa

 [1943 rows x 5 columns],
 'airfrance': airfrance       date       open      close   volume       name
 0         2019-01-02  47.388512  46.813557   491659  airfrance
 1         2019-01-03  46.803471  45.875469   606939  airfrance
 2         2019-01-04  46.642078  46.742947   559640  airfrance
 3         2019-01-07  46.894253  47.681034   512468  airfrance
 4         2019-01-08  47.711296  48.649380   544552  airfrance
 ...              ...        ...        ...      ...        ...
 1954      2026-08-19  11.810000  11.755000   811936  airfrance
 1955      2026-08-20  11.685000  11.380000  1115227  airfrance
 1956      2026-08-21  11.380000  11.500000  1095651  airfrance
 1957      2026-08-24  11.460000  11.625000  1476849  airfrance
 1958      2026-08-25  11.825000  12.065000  1459875  airfrance

 [1958 rows x 5 columns],
 'iag': iag        date      open     close    volume name
 0    2019-01-02  6.684923  6.723283   4537405  iag
 1    2019-01-03  6.635186  6.418684   6795077  iag
 2    2019-01-04  6.516755  6.547852   4278054  iag
 3    2019-01-07  6.666406  6.645145   3411969  iag
 4    2019-01-08  6.669961  6.635836   5906737  iag
 ...         ...       ...       ...       ...  ...
 1922 2026-08-19  4.991357  4.999842   6451126  iag
 1923 2026-08-20  4.982363  4.877730   7713245  iag
 1924 2026-08-21  4.911619  4.936385   7754056  iag
 1925 2026-08-24  4.948191  5.051338   5647481  iag
 1926 2026-08-25  5.097957  5.164839  10135293  iag

 [1927 rows x 5 columns],
 'brent': brent       date       open      close   name
 0     2019-01-02  47.333125  47.907329  brent
 1     2019-01-03  48.394772  49.434062  brent
 2     2019-01-04  48.793127  50.091833  brent
 3     2019-01-07  50.267594  50.243439  brent
 4     2019-01-08  50.203222  51.150994  brent
 ...          ...        ...        ...    ...
 1920  2026-08-19  78.872661  79.123036  brent
 1921  2026-08-20  78.378320  80.333824  brent
 1922  2026-08-21  79.854084  80.759138  brent
 1923  2026-08-24  80.171342  78.902128  brent
 1924  2026-08-25  78.999183  75.914835  brent

 [1925 rows x 4 columns],
 'gbpeur': gbpeur       date     open    close    name
 0      2019-01-01  1.11000  1.10790  gbpeur
 1      2019-01-02  1.11254  1.11264  gbpeur
 2      2019-01-03  1.10610  1.10570  gbpeur
 3      2019-01-04  1.10849  1.10851  gbpeur
 4      2019-01-07  1.11576  1.11593  gbpeur
 ...           ...      ...      ...     ...
 1986   2026-08-19  1.16921  1.16928  gbpeur
 1987   2026-08-20  1.16492  1.16497  gbpeur
 1988   2026-08-21  1.16721  1.16727  gbpeur
 1989   2026-08-24  1.16868  1.16875  gbpeur
 1990   2026-08-25  1.16872  1.16878  gbpeur

 [1991 rows x 4 columns],
 'usdeur': usdeur       date     open    close    name
 0      2019-01-01  0.87000  0.87009  usdeur
 1      2019-01-02  0.87250  0.87247  usdeur
 2      2019-01-03  0.88360  0.88354  usdeur
 3      2019-01-04  0.87789  0.87788  usdeur
 4      2019-01-07  0.87620  0.87639  usdeur
 ...           ...      ...      ...     ...
 1985   2026-08-19  0.86379  0.86360  usdeur
 1986   2026-08-20  0.85650  0.85662  usdeur
 1987   2026-08-21  0.85561  0.85559  usdeur
 1988   2026-08-24  0.85580  0.85605  usdeur
 1989   2026-08-25  0.85701  0.85702  usdeur

 [1990 rows x 4 columns]}

In [10]:
# Dropping gbpeur, usdeur frames which are no longer needed.

forex = ['gbpeur', 'usdeur']

for key in forex:
    try:
        data.pop(key, None)
    except KeyError:
        continue

In [11]:
# Checking for duplicated rows and dtypes

for key in data.keys():
    display(data[key].dtypes, data[key].duplicated().value_counts(dropna = False))

ryanair
date      datetime64[s]
open            float64
close           float64
volume            int64
name                str
dtype: object

False    1943
Name: count, dtype: int64

easyjet
date      datetime64[s]
open            float64
close           float64
volume            int64
name                str
dtype: object

False    1932
Name: count, dtype: int64

wizzair
date      datetime64[s]
open            float64
close           float64
volume            int64
name                str
dtype: object

False    1932
Name: count, dtype: int64

lufthansa
date      datetime64[s]
open            float64
close           float64
volume            int64
name                str
dtype: object

False    1943
Name: count, dtype: int64

airfrance
date      datetime64[s]
open            float64
close           float64
volume            int64
name                str
dtype: object

False    1958
Name: count, dtype: int64

iag
date      datetime64[s]
open            float64
close           float64
volume            int64
name                str
dtype: object

False    1927
Name: count, dtype: int64

brent
date     datetime64[s]
open           float64
close          float64
name               str
dtype: object

False    1925
Name: count, dtype: int64

In [12]:
# Converting name columns to category dtype.

def to_cat(df):
    for key in df.keys():
        df[key]['name'] = df[key]['name'].astype('category')
    return df

to_cat(data)

{'ryanair': ryanair       date       open      close  volume     name
 0       2019-01-02   9.819802   9.914224   24940  ryanair
 1       2019-01-03   9.980319   9.961435   17167  ryanair
 2       2019-01-04   9.895339   9.772593   23132  ryanair
 3       2019-01-07  10.088905  10.206931    7682  ryanair
 4       2019-01-08   9.923667  10.320236    4863  ryanair
 ...            ...        ...        ...     ...      ...
 1939    2026-08-19  24.200001  23.250000   17135  ryanair
 1940    2026-08-20  24.150000  22.990000   23900  ryanair
 1941    2026-08-21  23.400000  23.500000    7922  ryanair
 1942    2026-08-24  23.500000  23.160000   18057  ryanair
 1943    2026-08-25  24.059999  23.510000    4772  ryanair

 [1943 rows x 5 columns],
 'easyjet': easyjet       date       open      close   volume     name
 0       2019-01-02  12.348530  12.244087  1424927  easyjet
 1       2019-01-03  12.127932  11.991049  1536053  easyjet
 2       2019-01-04  12.076653  12.253984  2279479  easyjet
 3       2019-01-07  12.389839  12.258003  3446572  easyjet
 4       2019-01-08  12.156203  12.760855  2908500  easyjet
 ...            ...        ...        ...      ...      ...
 1927    2026-08-19   7.887490   7.836515  5812726  easyjet
 1928    2026-08-20   7.828262   7.814619  4505935  easyjet
 1929    2026-08-21   7.855323   7.832381  5359772  easyjet
 1930    2026-08-24   7.872228   7.875038  3777491  easyjet
 1931    2026-08-25   7.888860   7.900953  7154231  easyjet

 [1932 rows x 5 columns],
 'wizzair': wizzair       date       open      close  volume     name
 0       2019-01-02  31.006490  30.619853  291417  wizzair
 1       2019-01-03  30.860189  30.705289  223224  wizzair
 2       2019-01-04  31.248333  32.202216  268074  wizzair
 3       2019-01-07  32.546718  32.685589  449709  wizzair
 4       2019-01-08  32.588324  32.573386  229536  wizzair
 ...            ...        ...        ...     ...      ...
 1927    2026-08-19  12.194860  12.289133  374549  wizzair
 1928    2026-08-20  12.231660  12.034141  445533  wizzair
 1929    2026-08-21  12.080623  12.373061  312633  wizzair
 1930    2026-08-24  12.563309  12.377063  372688  wizzair
 1931    2026-08-25  12.341683  12.681263  630467  wizzair

 [1932 rows x 5 columns],
 'lufthansa': lufthansa       date       open      close   volume       name
 0         2019-01-02  11.978454  11.882315  4470439  lufthansa
 1         2019-01-03  11.825232  11.572864  5565657  lufthansa
 2         2019-01-04  11.699047  11.885319  4585005  lufthansa
 3         2019-01-07  11.996482  11.906351  4008106  lufthansa
 4         2019-01-08  11.966438  12.089618  6094122  lufthansa
 ...              ...        ...        ...      ...        ...
 1939      2026-08-19   7.880000   7.852000  2650648  lufthansa
 1940      2026-08-20   7.852000   7.618000  5143992  lufthansa
 1941      2026-08-21   7.650000   7.606000  7208816  lufthansa
 1942      2026-08-24   7.638000   7.786000  4491675  lufthansa
 1943      2026-08-25   7.844000   7.982000  5288313  lufthansa

 [1943 rows x 5 columns],
 'airfrance': airfrance       date       open      close   volume       name
 0         2019-01-02  47.388512  46.813557   491659  airfrance
 1         2019-01-03  46.803471  45.875469   606939  airfrance
 2         2019-01-04  46.642078  46.742947   559640  airfrance
 3         2019-01-07  46.894253  47.681034   512468  airfrance
 4         2019-01-08  47.711296  48.649380   544552  airfrance
 ...              ...        ...        ...      ...        ...
 1954      2026-08-19  11.810000  11.755000   811936  airfrance
 1955      2026-08-20  11.685000  11.380000  1115227  airfrance
 1956      2026-08-21  11.380000  11.500000  1095651  airfrance
 1957      2026-08-24  11.460000  11.625000  1476849  airfrance
 1958      2026-08-25  11.825000  12.065000  1459875  airfrance

 [1958 rows x 5 columns],
 'iag': iag        date      open     close    volume name
 0    2019-01-02  6.684923  6.723283   4537405  iag
 1    2019-01-03  6.635186  6.418684   6795077  iag
 2    2019-01-04  6.516755  6.547852   4278054  iag
 3    2019-01-07  6.666406  6.645145   3411969  iag
 4    2019-01-08  6.669961  6.635836   5906737  iag
 ...         ...       ...       ...       ...  ...
 1922 2026-08-19  4.991357  4.999842   6451126  iag
 1923 2026-08-20  4.982363  4.877730   7713245  iag
 1924 2026-08-21  4.911619  4.936385   7754056  iag
 1925 2026-08-24  4.948191  5.051338   5647481  iag
 1926 2026-08-25  5.097957  5.164839  10135293  iag

 [1927 rows x 5 columns],
 'brent': brent       date       open      close   name
 0     2019-01-02  47.333125  47.907329  brent
 1     2019-01-03  48.394772  49.434062  brent
 2     2019-01-04  48.793127  50.091833  brent
 3     2019-01-07  50.267594  50.243439  brent
 4     2019-01-08  50.203222  51.150994  brent
 ...          ...        ...        ...    ...
 1920  2026-08-19  78.872661  79.123036  brent
 1921  2026-08-20  78.378320  80.333824  brent
 1922  2026-08-21  79.854084  80.759138  brent
 1923  2026-08-24  80.171342  78.902128  brent
 1924  2026-08-25  78.999183  75.914835  brent

 [1925 rows x 4 columns]}

In [13]:
# Creating the final tables before loading the data to the SQL server.

def staging(df):
    airlines = []
    for key in df.keys():
        if key != 'brent':
            airlines.append(df[key])
        else:
            brent = df[key]
    combined_airlines = pd.concat(airlines, axis = 0)
    return combined_airlines, brent

airlines, brent = staging(data)

In [16]:
from sqlalchemy import create_engine

server = '.'
database = 'AirlineOilProject'

connection_string = f'mssql+pyodbc://@{server}/{database}?driver=ODBC+Driver+18+for+SQL+Server&trusted_connection=yes&TrustServerCertificate=yes'

engine = create_engine(connection_string)

In [18]:
airlines.to_sql('fact_airline_prices', con = engine, if_exists = 'replace', index = False)
brent.to_sql('dim_brent', con = engine, if_exists = 'replace', index = False)

353